package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"

	"github.com/99designs/gqlgen/graphql"
	"github.com/skinnykaen/robbo_student_personal_account.git/package/auth"
	"github.com/skinnykaen/robbo_student_personal_account.git/package/models"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// SingIn is the resolver for the SingIn field.
func (r *mutationResolver) SingIn(ctx context.Context, input models.SignInInput) (models.SignInResult, error) {
	ginContext, getGinContextErr := GinContextFromContext(ctx)
	if getGinContextErr != nil {
		return nil, getGinContextErr
	}
	client := auth.ClientInfo{}
	if ginContext != nil && ginContext.Request != nil {
		client.UserAgent = ginContext.Request.UserAgent()
		client.IPAddress = ginContext.ClientIP()
	}
	accessToken, refreshToken, err := r.authDelegate.SignIn(input.Email, input.Password, uint(input.UserRole), client)
	if err != nil {
		ext := map[string]interface{}{"code": signInErrorCode(err)}
		if errors.Is(err, auth.ErrUserInactive) {
			ext["code"] = "USER_INACTIVE"
			if inactive, ok := auth.AsAccountInactive(err); ok && inactive.HasBan {
				ban := map[string]interface{}{
					"reason":      inactive.Reason,
					"isPermanent": inactive.IsPermanent,
					"expiresAt":   nil,
				}
				if inactive.ExpiresAt != nil {
					ban["expiresAt"] = inactive.ExpiresAt.UTC().Format("2006-01-02T15:04:05Z07:00")
				}
				ext["ban"] = ban
			}
		}
		return nil, &gqlerror.Error{
			Path:       graphql.GetPath(ctx),
			Message:    err.Error(),
			Extensions: ext,
		}
	}
	setRefreshToken(refreshToken, ginContext)
	return &models.SingInResponse{
		AccessToken: accessToken,
	}, nil
}

// SingOut is the resolver for the SingOut field.
func (r *mutationResolver) SingOut(ctx context.Context) (*models.Error, error) {
	ginContext, getGinContextErr := GinContextFromContext(ctx)
	if getGinContextErr != nil {
		return nil, getGinContextErr
	}
	if refreshToken, err := getRefreshToken(ginContext); err == nil {
		_ = r.authDelegate.SignOut(refreshToken)
	}
	setRefreshToken("", ginContext)
	return &models.Error{}, nil
}

// Refresh is the resolver for the Refresh field.
func (r *mutationResolver) Refresh(ctx context.Context) (models.SignInResult, error) {
	ginContext, getGinContextErr := GinContextFromContext(ctx)
	if getGinContextErr != nil {
		return nil, getGinContextErr
	}
	refreshToken, err := getRefreshToken(ginContext)
	if err != nil {
		return nil, &gqlerror.Error{
			Path:    graphql.GetPath(ctx),
			Message: err.Error(),
			Extensions: map[string]interface{}{
				"code": "401",
			},
		}
	}

	newAccessToken, newRefreshToken, err := r.authDelegate.RefreshToken(refreshToken)
	if err != nil {
		return nil, &gqlerror.Error{
			Path:    graphql.GetPath(ctx),
			Message: err.Error(),
			Extensions: map[string]interface{}{
				"code": "500",
			},
		}
	}
	if newRefreshToken != "" {
		setRefreshToken(newRefreshToken, ginContext)
	}
	return &models.SingInResponse{
		AccessToken: newAccessToken,
	}, nil
}
